name: Deploy Jupyter Book

on:
  push:
    branches:
      - main  # 监听 main 分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装 Jupyter Book
        run: |
          pip install jupyter-book ghp-import

      - name: 构建 Jupyter Book
        run: jupyter-book build .

      - name: 部署到 GitHub Pages
        run: |
          ghp-import -n -p -f _build/html
