name: Deploy Jupyter Book

on:
  push:
    branches:
      - main

permissions:
  contents: write  # 允许写入仓库内容
  pages: write
  id-token: write  # 允许 GitHub Actions 访问 Pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Jupyter Book
        run: pip install jupyter-book ghp-import

      - name: Build Jupyter Book
        run: jupyter-book build .

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          ghp-import -n -p -f -o _build/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
